### ISSUE TITLE
PDF export

### ISSUE THREAD

**Issue by Tensho** [dabrorius/jobless#13]
Sometimes it's not enough to provide your personal site link with beautiful resume. Many companies require pdf/doc CV file (with blackjack and hookers) to attach it to an internal resource management system or send it to the customer, who doesn't know anything technical (e.g. browsers) except his kangaroo domain.

**Comment by dabrorius** [comment]
This was the original idea, however all the gems that do HTML to PDF conversion have [wkhtmltopdf](http://wkhtmltopdf.org/) as a dependency, which is a bit inconvenient in my opinon. On the other hand, you can convert HTML to PDF via any browser, without too much effort.

**Comment by Tensho** [comment]
Do you mean services like [pdfcrowd](http://pdfcrowd.com/#convert_by_upload)? I've just thought about [prawn](https://github.com/prawnpdf/prawn/blob/master/prawn.gemspec), but looks like you are totally right,YAGNI. The issue is settled.

**Comment by dabrorius** [comment]
Yeah, I was a bit lazy so I wanted to re-use the HTML template for generating the PDF too. In that case we would need some gem that does HTML -> PDF which depend on wkhtmltopdf library to be installed on local machine. We could use prawn, but in that case we would need another 'template' for generating the PDF, which complicates things a bit when user wants to override the style, they can't simply provide another CSS file any more.
I would love to see a ruby-only solution for HTML -> PDF conversion if something like that exists.

**Comment by Tensho** [comment]
I don't think another kind of the template is so bad idea, and **prawn** is real only-ruby solution, no extra dependencies (packages). And we can handle styles only for html. Anyway, right now I also don't thinks it worths the efforts.
You're free to reopen on demand.
